### ISSUE TITLE
Feature Request: Clear Windows with Flashing Status

### ISSUE THREAD

**Issue by ReanimationXP** [dechamps/RudeWindowFixer#17]
Hello,

I know it's unrelated to the bug this project addresses, but it would be helpful if (a) there was a tray icon to provoke RudeWindowFixer into doing it's thing, and (b) if there was also a menu option on it to clear all windows in the Flashing / HaveFlashed status.

Some apps like Outlook, if you have several messages open, will launch on sign in, open 20 windows in the Flashing status, and while they may only flash 3 times, the taskbar will stay 'popped' from AutoHide status until all of them are manually cleared, which means clicking on each individual window and giving it focus. In Win10/11 this is even more cumbersome than usual because they hide sub-windows like emails behind the one Outlook icon for the whole instance, so now it's either two clicks to clear each one, or this stupid "Hover over the Outlook icon then hope you can move to and click the right window before the popup disappears" dance, for every single one. Only after they have all been cleared will the taskbar retract.

Is this something you might consider adding as additional functionality?  Otherwise I'll have to come up with something myself, as I've encountered this often enough it's become a problem.

**Comment by dechamps** [comment]
I understand the issue (and I do experience it myself from time to time), but that doesn't seem like something that would be in scope for RudeWindowFixer. It would make more sense for this to be handled by a different tool.
