### ISSUE TITLE
Not an issue, question about taskbar hide timeout

### ISSUE THREAD

**Issue by crixionz** [dechamps/RudeWindowFixer#9]
Hi. Sorry, I'm kinda hijacking this, but you seem to really know stuff around the taskbar auto-hiding topic.
I did a lot of googling but couldn't find a proper answer that worked. I was wondering: 
Is there something like a registry entry which I can use to make the taskbar stay **un**hidden for longer, i.e. increase delay until the taskbar disappears again? 

Why?
I actually want to use this to have the auto-hide option enabled, but prevent the taskbar from hiding indefinitely (or for a long time at least). This might sound stupid, but I actually have a transparent taskbar and when I maximize a window, it doesn't go 'under' the transparent taskbar but stops above like this: 
▼
![image](https://user-images.githubusercontent.com/62850893/209664648-f3e66c24-cd20-46e2-a50e-793e23c1a2de.png) 

where I can see my wallpaper poking through at the bottom,
while I would rather have it look like this: 
▼
![image](https://user-images.githubusercontent.com/62850893/209664817-68fd2399-dc0e-44d4-8d19-36acf8dcf4ec.png)
Having auto-hide enabled gives me this look, but it obviously hides the taskbar (duh) after a second, which I find annoying.

Anyway, thank you for taking time to read thru this and I understand if you can't reply. 
I will close this immediately so it doesn't pop up with the other issues.

**Comment by dechamps** [comment]
If you didn't find anything online already, that probably means the delay is hardcoded (or the registry key is hardcoded and undocumented). You'd likely have to reverse engineer the taskbar code to find out, similarly to what I did for RudeWindowFixer.

If there is no registry key and the delay is hardcoded into the binary instead, modifying the delay could involve altering the binary which might get messy fast (e.g. it will not survive Windows updates).

**Comment by crixionz** [comment]
Thank you for the prompt reply! Well, one guy said the key `ThumbnailLivePreviewHoverTime` would do that, but it didn't, unsurprisingly so with the 'thumbnail' in there. 
Okay, so I'm out of luck probably. Still, thanks alot! 
At the top of your head, do think it is possible to somehow make a window extend past the taskbar margin, i.e. go 'under' the taskbar?

**Comment by dechamps** [comment]
I don't know. I guess you'd need to find some kind of way of altering what applications see when they query [`SPI_GETWORKAREA`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfoa) and/or [`GetMonitorInfo`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmonitorinfoa). Not sure that can be done without resorting to heavy artillery such as a [Windhawk](https://windhawk.net/) mod.

**Comment by crixionz** [comment]
Okay thank you very much for sharing your thoughts!
